# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: my-personal-computer

steps:
  - script: |
      if (Test-Path 'extensions.csproj') {
          dotnet build extensions.csproj --runtime win-x64 --output ./bin
      }
    displayName: 'Build extensions'
    # No shell property needed; defaults to PowerShell on Windows agents

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.10'
    inputs:
      versionSpec: 3.10 # Functions V2 supports Python 3.6 as of today

  - script: |
      python -m pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: 'Install application dependencies'
    # No shell property needed; defaults to PowerShell on Windows agents

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop