trigger:
- master

pool: 
  name: my-personal-computer

steps:
  - script: |
      if exist extensions.csproj (
          dotnet build extensions.csproj --runtime win-x64 --output ./bin
      )
    displayName: 'Build extensions'
  
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.10
    displayName: 'Use Python 3.10'

  - script: |
      python -m pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: 'Install application dependencies'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop